"""KONG ARGENTINO - Constantes de gameplay"""
VIDAS = 3
VELOCIDAD_JUGADOR = 2
VELOCIDAD_JUGADOR_ESCALERA = 2
VELOCIDAD_BARRILES = 2
GRAVEDAD = 0.95
SALTO = -16
SALTO_ESCALERA = -10
BARRILES_CADA = 80
TIEMPO_PODER = 300
PUNTUACION_POR_CERVEZA = 10
PUNTUACION_POR_NIVEL = 1000
PUNTUACION_POR_BARRIL_ROTO = 150
MULTIPLICADOR_COMBO_MAX = 5
TIEMPO_COMBO = 120
INVENCIBILIDAD_DESPUES_GOLPE = 120
TIEMPO_RESPAWN = 60
TIEMPO_ATAQUE = 20
DISTANCIA_ATAQUE = 40

# v4.0
PUNTUACION_POR_BARRIL_SALTADO = 25
TIEMPO_PARPADEO_INVENCIBLE = 4
MAX_PARTICULAS = 300
TIEMPO_FREEZE_PANTALLA = 8
VELOCIDAD_NUBES = 0.3
TIEMPO_ANIMACION_MUERTE = 90
SHAKE_DURACION = 18
SHAKE_INTENSIDAD = 5

# v4.2 - Física
MULTIPLICADOR_GRAVEDAD = 0.3
MULTIPLICADOR_SALTO = 0.7
MULTIPLICADOR_SALTO_ESCALERA = 0.8
VEL_MAX_CAIDA = 5
TIEMPO_PEGADO_TECHO = 60
MULTIPLICADOR_GRAVEDAD_BORRACHO = 0.3
VEL_MAX_CAIDA_BORRACHO = 5
