"""KONG ARGENTINO - Constantes de pantalla y versión"""
VERSION = "4.0.0"
NOMBRE_JUEGO = "KONG ARGENTINO"
NOMBRE_JUGADOR = "Mario"

ANCHO = 1024
ALTO = 768
FPS = 60
DURACION_CELEBRACION_RESCATE = FPS * 10
