"""KONG ARGENTINO - Tamaños de sprites"""
TAMANIO_JUGADOR  = (32, 38)
TAMANIO_BARRIL   = (32, 32)
TAMANIO_CERVEZA  = (20, 20)
TAMANIO_PODER    = (24, 24)
TAMANIO_KONG     = (80, 90)
TAMANIO_PRINCESA = (32, 38)
TAMANIO_BORRACHO = (32, 32)

# Compatibilidad
TAMANO_JUGADOR  = TAMANIO_JUGADOR
TAMANO_BARRIL   = TAMANIO_BARRIL
TAMANO_CERVEZA  = TAMANIO_CERVEZA
TAMANO_PODER    = TAMANIO_PODER
TAMANO_KONG     = TAMANIO_KONG
TAMANO_PRINCESA = TAMANIO_PRINCESA
TAMANO_BORRACHO = TAMANIO_BORRACHO
