"""
KONG ARGENTINO - Configuración Centralizada
Módulo principal de configuración y constantes
"""
from .pantalla import *
from .gameplay import *
from .dificultad import *
from .colores import *
from .tamanos import *
from .persistencia import *

__all__ = [
    # Pantalla
    'VERSION', 'NOMBRE_JUEGO', 'NOMBRE_JUGADOR',
    'ANCHO', 'ALTO', 'FPS', 'DURACION_CELEBRACION_RESCATE',
    # Gameplay
    'VIDAS', 'VELOCIDAD_JUGADOR', 'VELOCIDAD_JUGADOR_ESCALERA',
    'VELOCIDAD_BARRILES', 'GRAVEDAD', 'SALTO', 'SALTO_ESCALERA',
    'BARRILES_CADA', 'TIEMPO_PODER', 'PUNTUACION_POR_CERVEZA',
    'PUNTUACION_POR_NIVEL', 'PUNTUACION_POR_BARRIL_ROTO',
    'MULTIPLICADOR_COMBO_MAX', 'TIEMPO_COMBO', 'INVENCIBILIDAD_DESPUES_GOLPE',
    'TIEMPO_RESPAWN', 'TIEMPO_ATAQUE', 'DISTANCIA_ATAQUE',
    'PUNTUACION_POR_BARRIL_SALTADO', 'TIEMPO_PARPADEO_INVENCIBLE',
    'MAX_PARTICULAS', 'TIEMPO_FREEZE_PANTALLA', 'VELOCIDAD_NUBES',
    'TIEMPO_ANIMACION_MUERTE', 'SHAKE_DURACION', 'SHAKE_INTENSIDAD',
    'MULTIPLICADOR_GRAVEDAD', 'MULTIPLICADOR_SALTO', 'MULTIPLICADOR_SALTO_ESCALERA',
    'VEL_MAX_CAIDA', 'TIEMPO_PEGADO_TECHO', 'MULTIPLICADOR_GRAVEDAD_BORRACHO',
    'VEL_MAX_CAIDA_BORRACHO',
    # Dificultad
    'DIFICULTAD_NIVEL',
    # Colores
    'COLORES',
    # Tamaños
    'TAMANIO_JUGADOR', 'TAMANIO_BARRIL', 'TAMANIO_CERVEZA', 'TAMANIO_PODER',
    'TAMANIO_KONG', 'TAMANIO_PRINCESA', 'TAMANIO_BORRACHO',
    'TAMANO_JUGADOR', 'TAMANO_BARRIL', 'TAMANO_CERVEZA', 'TAMANO_PODER',
    'TAMANO_KONG', 'TAMANO_PRINCESA', 'TAMANO_BORRACHO',
    # Persistencia
    'ARCHIVO_HIGHSCORE', 'ARCHIVO_PERFIL',
]
